package com.xxx.myapplication.model.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xxx.myapplication.model.db.entry.WebSocketMessageBean;

import com.xxx.myapplication.model.db.greendao.WebSocketMessageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig webSocketMessageBeanDaoConfig;

    private final WebSocketMessageBeanDao webSocketMessageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        webSocketMessageBeanDaoConfig = daoConfigMap.get(WebSocketMessageBeanDao.class).clone();
        webSocketMessageBeanDaoConfig.initIdentityScope(type);

        webSocketMessageBeanDao = new WebSocketMessageBeanDao(webSocketMessageBeanDaoConfig, this);

        registerDao(WebSocketMessageBean.class, webSocketMessageBeanDao);
    }
    
    public void clear() {
        webSocketMessageBeanDaoConfig.clearIdentityScope();
    }

    public WebSocketMessageBeanDao getWebSocketMessageBeanDao() {
        return webSocketMessageBeanDao;
    }

}
